server:
  error:
    include-message: always
    include-binding-errors: always

spring:
#   jackson:
#     serialization:
#         FAIL_ON_EMPTY_BEANS: false
  datasource:
    username: admin
    password: "admin"
    url: jdbc:mysql://localhost:3306/onlinebank?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
